### ISSUE TITLE
Launch Details: Visualisierung der Sensordaten

### ISSUE THREAD

**Issue by LeonTimmer99** [JonaSchwei01/th-owl-rocketscience-webapp#10]
Die Sensordaten, welche von der Rakete geliefert werden, müssen in ein passendes Format gebracht werden, das es ermöglicht, diese im Dashboard anzuzeigen.

**Comment by JonaSchwei01** [comment]
> z.B mit Chart.js (https://www.chartjs.org/)

Chart.js bzw. ng2-charts machen aktuell Probleme bei der Installation aufgrund der abhängigen Dependencies.

**Comment by JonaSchwei01** [comment]
> > z.B mit Chart.js (https://www.chartjs.org/)
> 
> Chart.js bzw. ng2-charts machen aktuell Probleme bei der Installation aufgrund der abhängigen Dependencies.

Alternative: (Plotly.js)[https://www.npmjs.com/package/angular-plotly.js]
