### ISSUE TITLE
Launches: create new launches (via button)

### ISSUE THREAD

**Issue by LeonTimmer99** [JonaSchwei01/th-owl-rocketscience-webapp#6]
Kalenderliste mit bevorstehenden Abschuss Terminen

**Comment by JonaSchwei01** [comment]
Implementierung der [Launch-Übersicht als CodePen](https://codepen.io/jonaschwei01/pen/ExMBdYg)
Implementierung der [Launch-Detailseite](https://codepen.io/jonaschwei01/pen/abMgRQq)

Denkbar wäre es, mit Bootstrap ein Modal zu erstellen (als Popup), welches die Detailseite anzeigt. Oder alternativ eine separate Unterseite ...

**Comment by JonaSchwei01** [comment]
@LeonTimmer99 In der Übersichstseite für die Launches müssen wir mit den Bindings bzw. vielmehr Directives von Angular arbeiten und können leider nicht einfach nur den HTML-Code mehrfach duplizieren 🫠.
Da gibt es soweit ich weiß das Directive "ngRepeat". Vielleicht könnte das schon funktionieren. 

Aber es müssen aber trotzdem alle Komponenten individuell ansteuerbar sein, wofür vermutlich eine Datenbank/Array mit allen Launches sowie deren Details (Flugdaten, GPX-Daten für Trajtektorie, Fotos, etc.) vonnöten sein wird.

**Comment by JonaSchwei01** [comment]
Habe dafür übrigens schon einen neuen Branch erstellt, s.o.
