### ISSUE TITLE
CesiumJS: implement backend data structure for GPS/GPX data for the trajectory

### ISSUE THREAD

**Issue by LeonTimmer99** [JonaSchwei01/th-owl-rocketscience-webapp#7]
GPS Daten, die von der Rakete gesendet werden, sollen im GPX Format abgespeichert werden, damit diese in Cesium JS importiert werden können.

**Comment by JonaSchwei01** [comment]
Für die Ausarbeitung werden Beispiel-Daten verwendet. Die Echtzeitübertragung und das direkte Abspeichern/Auslesen der GPX-Daten wird als Ausblick festgehalten.
